// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "juliabase_types.h"
#include <Rcpp.h>

using namespace Rcpp;

// juliabase_init
void juliabase_init();
RcppExport SEXP _juliabase_juliabase_init() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    juliabase_init();
    return R_NilValue;
END_RCPP
}
// foo
jl_value_t* foo();
RcppExport SEXP _juliabase_foo() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(foo());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_juliabase_juliabase_init", (DL_FUNC) &_juliabase_juliabase_init, 0},
    {"_juliabase_foo", (DL_FUNC) &_juliabase_foo, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_juliabase(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
