# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
juliabase_init <- function() {
    invisible(.Call('_juliabase_juliabase_init', PACKAGE = 'juliabase'))
}

#' @export
foo <- function() {
    invisible(.Call('_juliabase_foo', PACKAGE = 'juliabase'))
}

